project:
  type: website
  output-dir: docs

website:
  title: "priyankanairmlblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/priyankanair2001/
      - icon: instagram
        href: https://www.instagram.com/hokiepriya/
format:
  html:
    theme: theme.scss
    css: styles.css

editor: visual

